In [68]:
import pandas as pd 
df = pd.read_csv("Mine.csv")
print(df.to_string)

<bound method DataFrame.to_string of     Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60          NaN  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60          NaN   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN>

In [69]:
Missing_values_in_each_column = df.isna().sum()
print(Missing_values_in_each_column  )

duplicates = df.duplicated()
print(duplicates)

Duration    0
Date        2
Pulse       1
Maxpulse    2
Calories    4
dtype: int64
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
dtype: bool

In [70]:
# To hold empty cells in the date culomn we fill the empty cells with the date tha appears most
date_mode = df['Date'].mode()[0]
# print(data_mode)
df.fillna({'Date' : date_mode } , inplace=True)

# print(df.isna().sum())
print(df)

Duration    0
Date        0
Pulse       1
Maxpulse    2
Calories    4
dtype: int64
    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60  2023/10/15'  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60  2023/10/15'   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [59]:
pd.set_option('display.max_rows', 32)

In [60]:
# to ensure the there are no wrong formate in the data ,we convert all the data in the date culomn to the same formate

# df['Date'] = pd.to_datetime(df['Date'], format='%Y/%m/%d', errors='coerce')
print(df)

    Duration         Date  Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.0     130.0     409.1
1         60  2023/10/02'  117.0     145.0     479.0
2         60  2023/10/03'  103.0     135.0     340.3
3         45  2023/10/04'  109.0     175.0     282.4
4         45  2023/10/05'  117.0     150.0     405.1
5         60  2023/10/06'  103.0     125.0     300.0
6         60  2023/10/07'  110.0     135.0     374.0
7        400  2023/10/08'  114.0     133.0       NaN
8         60  2023/10/09'  112.0     126.0     193.8
9         30  2023/10/10'  102.0     147.0     234.8
10        60  2023/10/11'  100.0     129.0     375.3
11        60  2023/10/12'  109.0     131.0     345.6
12        60  2023/10/13'  103.0     136.0     239.2
13        60  2023/10/15'  120.0       NaN     240.8
14        60  2023/10/15'  120.0     100.0     240.8
15        60  2023/10/16'    NaN     101.0     243.8
16        60  2023/10/17'  127.0     102.0     380.2
17        45     20231018  142.0     103.0     241.4
18        60  2023/10/19'  151.0     104.0       NaN
19        60  2023/10/20'  162.0     105.0     300.9
20        60  2023/10/21'  100.0     106.0     280.0
21        60  2023/10/22'  103.0     107.0       NaN
22        60  2023/10/15'  130.0     108.0     230.8
23        60  2023/10/24'  134.0       NaN     239.7
24        60  2023/10/25'  132.0     110.0     236.9
25        60  2023/10/26'  135.0     118.0     278.8
26        60  2023/10/27'  137.0     119.0     212.9
27        60  2023/10/28'  138.0     121.0     345.9
28        60  2023/10/29'  139.0     122.0     345.2
29        60  2023/10/15'   92.0     125.0     380.5
30        60  2023/10/31'   94.0     126.0       NaN

In [61]:
# replacing all the missing value in the pulse column with the mean value
mean_pulse = df['Pulse'].mean()
df.fillna({'Pulse' : mean_pulse}, inplace=True)
print(df)
# print(df.isna().sum())

    Duration         Date       Pulse  Maxpulse  Calories
0         60  2023/10/01'  110.000000     130.0     409.1
1         60  2023/10/02'  117.000000     145.0     479.0
2         60  2023/10/03'  103.000000     135.0     340.3
3         45  2023/10/04'  109.000000     175.0     282.4
4         45  2023/10/05'  117.000000     150.0     405.1
5         60  2023/10/06'  103.000000     125.0     300.0
6         60  2023/10/07'  110.000000     135.0     374.0
7        400  2023/10/08'  114.000000     133.0       NaN
8         60  2023/10/09'  112.000000     126.0     193.8
9         30  2023/10/10'  102.000000     147.0     234.8
10        60  2023/10/11'  100.000000     129.0     375.3
11        60  2023/10/12'  109.000000     131.0     345.6
12        60  2023/10/13'  103.000000     136.0     239.2
13        60  2023/10/15'  120.000000       NaN     240.8
14        60  2023/10/15'  120.000000     100.0     240.8
15        60  2023/10/16'  118.833333     101.0     243.8
16        60  2023/10/17'  127.000000     102.0     380.2
17        45     20231018  142.000000     103.0     241.4
18        60  2023/10/19'  151.000000     104.0       NaN
19        60  2023/10/20'  162.000000     105.0     300.9
20        60  2023/10/21'  100.000000     106.0     280.0
21        60  2023/10/22'  103.000000     107.0       NaN
22        60  2023/10/15'  130.000000     108.0     230.8
23        60  2023/10/24'  134.000000       NaN     239.7
24        60  2023/10/25'  132.000000     110.0     236.9
25        60  2023/10/26'  135.000000     118.0     278.8
26        60  2023/10/27'  137.000000     119.0     212.9
27        60  2023/10/28'  138.000000     121.0     345.9
28        60  2023/10/29'  139.000000     122.0     345.2
29        60  2023/10/15'   92.000000     125.0     380.5
30        60  2023/10/31'   94.000000     126.0       NaN

In [62]:
# filling the null values with the mean 
mean_maxpulse = df['Maxpulse'].mean()
df.fillna({'Maxpulse':mean_maxpulse}, inplace=True)
print(df)

    Duration         Date       Pulse    Maxpulse  Calories
0         60  2023/10/01'  110.000000  130.000000     409.1
1         60  2023/10/02'  117.000000  145.000000     479.0
2         60  2023/10/03'  103.000000  135.000000     340.3
3         45  2023/10/04'  109.000000  175.000000     282.4
4         45  2023/10/05'  117.000000  150.000000     405.1
5         60  2023/10/06'  103.000000  125.000000     300.0
6         60  2023/10/07'  110.000000  135.000000     374.0
7        400  2023/10/08'  114.000000  133.000000       NaN
8         60  2023/10/09'  112.000000  126.000000     193.8
9         30  2023/10/10'  102.000000  147.000000     234.8
10        60  2023/10/11'  100.000000  129.000000     375.3
11        60  2023/10/12'  109.000000  131.000000     345.6
12        60  2023/10/13'  103.000000  136.000000     239.2
13        60  2023/10/15'  120.000000  123.241379     240.8
14        60  2023/10/15'  120.000000  100.000000     240.8
15        60  2023/10/16'  118.833333  101.000000     243.8
16        60  2023/10/17'  127.000000  102.000000     380.2
17        45     20231018  142.000000  103.000000     241.4
18        60  2023/10/19'  151.000000  104.000000       NaN
19        60  2023/10/20'  162.000000  105.000000     300.9
20        60  2023/10/21'  100.000000  106.000000     280.0
21        60  2023/10/22'  103.000000  107.000000       NaN
22        60  2023/10/15'  130.000000  108.000000     230.8
23        60  2023/10/24'  134.000000  123.241379     239.7
24        60  2023/10/25'  132.000000  110.000000     236.9
25        60  2023/10/26'  135.000000  118.000000     278.8
26        60  2023/10/27'  137.000000  119.000000     212.9
27        60  2023/10/28'  138.000000  121.000000     345.9
28        60  2023/10/29'  139.000000  122.000000     345.2
29        60  2023/10/15'   92.000000  125.000000     380.5
30        60  2023/10/31'   94.000000  126.000000       NaN

In [63]:
# filling the Calories column with the median value of the column 
median_calories = df['Calories'].median()
df.fillna({'Calories':median_calories}, inplace=True)
print(df)

    Duration         Date       Pulse    Maxpulse  Calories
0         60  2023/10/01'  110.000000  130.000000     409.1
1         60  2023/10/02'  117.000000  145.000000     479.0
2         60  2023/10/03'  103.000000  135.000000     340.3
3         45  2023/10/04'  109.000000  175.000000     282.4
4         45  2023/10/05'  117.000000  150.000000     405.1
5         60  2023/10/06'  103.000000  125.000000     300.0
6         60  2023/10/07'  110.000000  135.000000     374.0
7        400  2023/10/08'  114.000000  133.000000     282.4
8         60  2023/10/09'  112.000000  126.000000     193.8
9         30  2023/10/10'  102.000000  147.000000     234.8
10        60  2023/10/11'  100.000000  129.000000     375.3
11        60  2023/10/12'  109.000000  131.000000     345.6
12        60  2023/10/13'  103.000000  136.000000     239.2
13        60  2023/10/15'  120.000000  123.241379     240.8
14        60  2023/10/15'  120.000000  100.000000     240.8
15        60  2023/10/16'  118.833333  101.000000     243.8
16        60  2023/10/17'  127.000000  102.000000     380.2
17        45     20231018  142.000000  103.000000     241.4
18        60  2023/10/19'  151.000000  104.000000     282.4
19        60  2023/10/20'  162.000000  105.000000     300.9
20        60  2023/10/21'  100.000000  106.000000     280.0
21        60  2023/10/22'  103.000000  107.000000     282.4
22        60  2023/10/15'  130.000000  108.000000     230.8
23        60  2023/10/24'  134.000000  123.241379     239.7
24        60  2023/10/25'  132.000000  110.000000     236.9
25        60  2023/10/26'  135.000000  118.000000     278.8
26        60  2023/10/27'  137.000000  119.000000     212.9
27        60  2023/10/28'  138.000000  121.000000     345.9
28        60  2023/10/29'  139.000000  122.000000     345.2
29        60  2023/10/15'   92.000000  125.000000     380.5
30        60  2023/10/31'   94.000000  126.000000     282.4

In [67]:
Missing_values_in_each_column = df.isna().sum()
print(Missing_values_in_each_column)

duplicates = df.duplicated()
print(duplicates)

Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
dtype: bool